### PR TITLE
add useDefaultName and description to Datastream Model

### PR DESCRIPTION
**Pull request by daniel-slaugh**
hydroserver2/hydroserver#112

### CODE REVIEW

**Comment by kjlippold** [comment]
Do we need to store whether the user used the default name and description on the backend? What if we just let the front end handle the name and description generation, whether it's the automated default or user generated, and pass those strings to the backend.

**Comment by horsburgh** [comment]
If @kjlippold suggestion is possible, I would prefer it. My preference is to store as little as possible in the database that isn't from SensorThings or ODM.

**Comment by daniel-slaugh** [comment]
@horsburgh Yes, it's possible. The approach would be regular text boxes on the datastream form page with buttons next to them that say something like 'Update name with current form data.' The downside is the user would have to click these buttons each time they create or update a datastream to populate the field with the default string, but with the benefit of a cleaner backend. Would you prefer that instead?

**Comment by horsburgh** [comment]
@daniel-slaugh - I think that's probably OK. The point is that the name and descriptions are just text fields in the database. How the values for those fields get set is up to the user. They can either click the button to automatically generate them, or they can type something else in. I think we would want to keep the clicking of the buttons to be optional because if someone sets the name or description deliberately, we don't want to clobber what they have set with an automatically generated string if they make an update to the metadata. They can always choose to click the button, which might pop something up that shows them the string that is auto-generated and they can either accept it or edit it right there before accepting.

**Comment by daniel-slaugh** [comment]
@kjlippold I updated the PR with your suggestion. I also added a 'revert' button for when the user is editing a datastream and wants to revert back to what they had if they don't like the auto-filled text. Here's a screenshot of what it looks like:
 
image

**Review by kjlippold — APPROVED** [review]

**Pull request merged**
