### PR TITLE
Added delete user endpoint and is_active filter to auth checks.

### PR DESCRIPTION
**Pull request by kjlippold**
Added delete user endpoint. The endpoint will set the user as inactive, which will prevent the user from logging in and hide sites they are the primary owner of from all requests. Once we have a task scheduler set up, we can add a task to delete the user's data after 30 days.

### CODE REVIEW

**Review by daniel-slaugh — APPROVED** [review]
Looks good - I created an account and a site then deleted that account. User and site were still in the database, but invisible to other users of the system. I confirmed I couldn't login as the deleted user afterwards. Then reactivated the account as admin and was able to continue using account.

**Comment by daniel-slaugh** [comment]
What's the expected behavior for a site shared with a secondary owner? Right now, if I assign a secondary to a site and then delete the primary owner, the site is still visible to guests, but only shows the secondary owner as an owner.

**Comment by horsburgh** [comment]
@daniel-slaugh - I see a couple of options for when the primary owner of a site deletes their account:
1. We delete (eventually) all of the sites and data for which that account is the primary owner. There should be a strongly written warning that this will occur and that must be clicked through. Perhaps they even have to type in "DELETE" to ensure they acknowledge what they are doing.
2. We transfer ownership to the first secondary owner. There's really no hierarchy or preference, so not sure which one should be chosen
3. We don't allow a user to delete their account until they have either deleted all of their sites or they have transferred primary ownership of all of their sites to another user.

I'm leaning toward number 1 with a strongly written warning that says - you really should either delete or transfer ownership of your sites before you go.

**Comment by daniel-slaugh** [comment]
@horsburgh Ken and I discussed and agree with you that number 1 seems like the best solution. We have the modal in place that makes the user type in 'delete my account and data.' I think all that's missing is updating the thing endpoints to prevent returning the things where the primary owner's account is deactivated. 
image

**Pull request merged**
